#!/usr/bin/env bash
#Configuring nginx with a permanent redirect

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sed -i ' /# as directory, then fall back to displaying a 404./a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
