#!/usr/bin/env bash
#Configuring nginx with a permanent redirect

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
service nginx restart
sed -i ' /# as directory, then fall back to displaying a 404./a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i ' /server_name _;/a error_page 404 /404.html;\nlocation = /404.html { \nroot /usr/share/nginx/html; \ninternal;\n}' /etc/nginx/sites-available/default
service nginx restart
