#!/usr/bin/env bash
#Automation the configuration of a new server a new webserver

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sed -i '/# as directory, then fall back to displaying a 404./a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /usr/share/nginx/html; \ninternal;\n}' /etc/nginx/sites-available/default
cp /etc/nginx/nginx.conf /etc/nginx/nginxbak.conf
sed -i '/http {/a add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
service nginx restart