#!/usr/bin/env bash
# HAProxy installation and configuration

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get install haproxy=2.6.\*
sed -i -e '$aENABLED=1\n' /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxybak.cfg
sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 11248-web-01 44.210.79.91 check\n\tserver 11248-web-02 100.26.217.114 check\n' /etc/haproxy/haproxy.cfg
service haproxy start