#!/usr/bin/env bash
#This script authenticates your ssh key pair copying it into servers authorized key files.
#Enables you log into the server via SSH without being prompted for a password.
ssh-copy-id ubuntu@44.211.33.72